update testing workflow

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -22,8 +22,7 @@ jobs:
         run: |
           ls ${{ github.workspace }}
       - name: Test
-        run: npm test
-        run: echo "Testing the project"
+        run: npm test && echo "Test passed" || echo "Test failed"
       - name: Build
         run: npm run build
       - run: echo "🍏 This job's status is ${{ job.status }}."
